image: Visual Studio 2017

platform: x86_64

clone_folder: c:\gopath\src\github.com\skycoin\skycoin

branches:
  only:
    - master

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - cmd: set PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\gopath\bin;C:\go\bin;%PATH%
    - cmd: set MSYSTEM=MINGW64

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  GOPATH: c:\gopath
  GOX_OUTPUT: .gox_output
  BUILD_DIR: build
  BUILDLIB_DIR: $BUILD_DIR/libskycoin
  LIB_DIR: lib
  CRAM_SHELL: "C:\\msys64\\usr\\bin\\sh.exe"
  CPPFLAGS: -D__USE_MINGW_ANSI_STDIO=1

cache:
    - 'electron\node_modules'
    - '%LOCALAPPDATA%\Yarn'
    - '%USERPROFILE%\.electron'

install:
    - cmd: go get github.com/gz-c/gox
    - ps: Install-Product node 8 x64
    - ps: cd electron
    - cmd: npm install --global electron-builder
    - cmd: npm install --global electron-download
    - cmd: npm install -g yarn
    - cmd: cd C:\gopath\src\github.com\skycoin\skycoin
    - cmd: make install-linters
    - cmd: make install-deps-libc
    - cmd: make install-deps-ui

build_script:
    - cmd: cd C:\gopath\src\github.com\skycoin\skycoin\electron
    - cmd: yarn install
    - cmd: bash ./build.sh "windows/amd64 windows/386"
    - ps: ls release\
    - ps: cd ..

after_build:
    - ps: 7z a skycoin.zip C:\gopath\src\github.com\skycoin\skycoin\electron\release\*
    - ps: ls *.zip

test: off

test_script:
    - cmd: make lint
    - cmd: make lint-ui
    - cmd: make test-ui

artifacts:
    - path: skycoin.zip
      name: published

    #deploy:
    #  provider: S3
    #  access_key_id: $(AWS_ACCESS_KEY_ID)
    #  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
    #  bucket: $(AWS_BUCKET)
    #  region: $(AWS_REGION)
    #  folder: wallet
    #  artifact: published
    #  unzip: true
    #  set_public: true
    #  on:
    #    branch: master
    #
    #
    #notifications:
    #  - provider: Email
    #    on_build_success: false
    #    on_build_failure: false
    #    on_build_status_changed: false
