version: '3.3'

services:

  integration-test-stable:
    container_name: integration-test-stable
    build:
      context: ./../../..
      dockerfile: ./docker/images/mainnet/Dockerfile
      args: 
        SCOMMIT: $SOURCE_COMMIT
        SBRANCH: $SOURCE_BRANCH
        
    image: skycoin-test
    expose:
      - "6420"
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet1:/wallet
      - skycoin-data1:/data/.skycoin
    command: "-db-path=/testdata/blockchain-180.db \
              -disable-networking=true \
              -download-peerlist=false \
              -db-read-only=true \
              -launch-browser=false \
              -enable-all-api-sets=true \
              -disable-header-check"
  
  integration-test-stable-disable-csrf:
    container_name: integration-test-stable-disable-csrf
    depends_on:
      - integration-test-stable
    image: skycoin-test
    expose:
      - "6420"
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet2:/wallet
      - skycoin-data2:/data/.skycoin
    command: "-db-path=/testdata/blockchain-180.db \
              -disable-networking=true \
              -download-peerlist=false \
              -db-read-only=true \
              -launch-browser=false \
              -enable-all-api-sets=true \
              -disable-csrf"

  integration-test-disable-wallet-api:
    container_name: integration-test-disable-wallet-api
    image: skycoin-test
    expose:
      - "6420"
    depends_on:
      - integration-test-stable
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet3:/wallet
      - skycoin-data3:/data/.skycoin
    command: "-disable-networking=true \
              -download-peerlist=false \
              -db-path=/testdata/blockchain-180.db \
              -db-read-only=true \
              -launch-browser=false \
              -enable-all-api-sets=true \
              -disable-api-sets=WALLET"

  integration-test-enable-seed-api:
    container_name: integration-test-enable-seed-api
    image: skycoin-test
    expose:
      - "6420"
    depends_on:
      - integration-test-stable
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet4:/wallet
      - skycoin-data4:/data/.skycoin
    command: "-disable-networking=true \
              -download-peerlist=false \
              -db-path=/testdata/blockchain-180.db \
              -db-read-only=true \
              -launch-browser=false \
              -enable-all-api-sets=true \
              -enable-api-sets=INSECURE_WALLET_SEED"
  
  integration-test-disable-gui:
    container_name: integration-test-disable-gui
    image: skycoin-test
    expose:
      - "6420"
    depends_on:
      - integration-test-stable
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet5:/wallet
      - skycoin-data5:/data/.skycoin
    command: "-disable-networking=true \
              -download-peerlist=false \
              -db-path=/testdata/blockchain-180.db \
              -db-read-only=true \
              -launch-browser=false \
              -enable-all-api-sets=true \
              -enable-api-sets=INSECURE_WALLET_SEED\
              -enable-gui=false"

  integration-test-auth:
    container_name: integration-test-auth
    image: skycoin-test
    expose:
      - "6420"
    depends_on:
      - integration-test-stable
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet6:/wallet
      - skycoin-data6:/data/.skycoin
    command: "-disable-networking=true \
              -download-peerlist=false \
              -db-path=/testdata/blockchain-180.db \
              -db-read-only=true \
              -launch-browser=false \
              -web-interface-username=foobar\
              -web-interface-password=abcdef123\
              -web-interface-plaintext-auth=true\
              -enable-all-api-sets=true \
              -disable-csrf"
  
  integration-test-db-no-unconfirmed:
    container_name: integration-test-db-no-unconfirmed
    depends_on: 
      - integration-test-stable
    image: skycoin-test
    expose:
      - "6420"
    volumes:
      - ./../../../src/api/integration/testdata:/testdata
      - skycoin-wallet7:/wallet
      - skycoin-data7:/data/.skycoin
    command: "-db-path=/testdata/blockchain-180.db \
              -disable-networking=true \
              -download-peerlist=false \
              -db-read-only=true \
              -launch-browser=false \
              -enable-all-api-sets=true \
              -disable-csrf"
  
  sut:
    build:
      context: ./../../..
      dockerfile: ./docker/images/mainnet/Dockerfile.test
    depends_on:
      - integration-test-stable
      - integration-test-stable-disable-csrf
      - integration-test-disable-wallet-api
      - integration-test-enable-seed-api
      - integration-test-disable-gui
      - integration-test-auth
      - integration-test-db-no-unconfirmed
    volumes:
      - skycoin-wallet1:/wallet-integration-test-stable
      - skycoin-wallet2:/wallet-integration-test-stable-disable-csrf
      - skycoin-wallet3:/wallet-integration-test-disable-wallet-api
      - skycoin-wallet4:/wallet-integration-test-enable-seed-api
      - skycoin-wallet5:/wallet-integration-test-disable-gui
      - skycoin-wallet6:/wallet-integration-test-auth
      - skycoin-wallet7:/wallet-integration-test-db-no-unconfirmed
      - skycoin-data1:/data/.skycoin-integration-test-stable
      - skycoin-data2:/data/.skycoin-integration-test-stable-disable-csrf
      - skycoin-data3:/data/.skycoin-integration-test-disable-wallet-api
      - skycoin-data4:/data/.skycoin-integration-test-enable-seed-api
      - skycoin-data5:/data/.skycoin-integration-test-disable-gui
      - skycoin-data6:/data/.skycoin-integration-test-auth
      - skycoin-data7:/data/.skycoin-integration-test-db-no-unconfirmed

    command: "bash ./docker-cloud-test.sh"

volumes:
  skycoin-data1:
    external: true
  skycoin-wallet1:
    external: true
  skycoin-data2:
    external: true
  skycoin-wallet2:
    external: true
  skycoin-data3:
    external: true
  skycoin-wallet3:
    external: true
  skycoin-data4:
    external: true
  skycoin-wallet4:
    external: true
  skycoin-data5:
    external: true
  skycoin-wallet5:
    external: true
  skycoin-data6:
    external: true
  skycoin-wallet6:
    external: true
  skycoin-data7:
    external: true
  skycoin-wallet7:
    external: true
